### ISSUE TITLE
Question about method 'moveToNeighbor' in SingleAgentStarsSIPP_Solver

### ISSUE THREAD

**Issue by losecanvas** [J-morag/MAPF#89]
I'm sorry to bother you。 I have a question, for ‘moveToNeighbor ’ in SIPP is about a judgment conditions' if (prevLocationRelevantInterval. End > = currInterval. Start - 1) ', The meaning of the judgment condition is because timeNow haven't meet 'currInterval' safety time interval, so will do wait, wait time is 1, so 'prevLocationRelevantInterval. End' must be able to tolerate more waiting time of 1s, In order to satisfy 'currInterval' after waiting

**Comment by losecanvas** [comment]
Another question is why only vertex conflicts and not edge conflicts are selected when calculating the safe time interval of locations.

**Comment by J-morag** [comment]
Hello losecanvas,

> I'm sorry to bother you。 I have a question, for ‘moveToNeighbor ’ in SIPP is about a judgment conditions' if (prevLocationRelevantInterval. End > = currInterval. Start - 1) ', The meaning of the judgment condition is because timeNow haven't meet 'currInterval' safety time interval, so will do wait, wait time is 1, so 'prevLocationRelevantInterval. End' must be able to tolerate more waiting time of 1s, In order to satisfy 'currInterval' after waiting

This is mostly correct. The only correction I would point out is that the minimal waiting time is calculated through `currInterval.start - 1` and it is not necessarily 1.

> Another question is why only vertex conflicts and not edge conflicts are selected when calculating the safe time interval of locations.

Only vertex constraints are considered because an edge constraint does not mean the vertex is unsafe. It could be unsafe to reach the vertex through some edge, but safe through another. Edge constraints are handled in 'moveIntoSafeInterval' using 'constraints.accepts()'.

**Comment by losecanvas** [comment]
thanks for your reply!
________________________________
发件人: ***@***.*** ***@***.***> 代表 J-morag ***@***.***>
发送时间: 2024年5月14日 16:03
收件人: J-morag/MAPF ***@***.***>
抄送: losecanvas ***@***.***>; Author ***@***.***>
主题: Re: [J-morag/MAPF] Question about method 'moveToNeighbor' in SingleAgentStarsSIPP_Solver (Issue #89)


Hello losecanvas,

I'm sorry to bother you。 I have a question, for ‘moveToNeighbor ’ in SIPP is about a judgment conditions' if (prevLocationRelevantInterval. End > = currInterval. Start - 1) ', The meaning of the judgment condition is because timeNow haven't meet 'currInterval' safety time interval, so will do wait, wait time is 1, so 'prevLocationRelevantInterval. End' must be able to tolerate more waiting time of 1s, In order to satisfy 'currInterval' after waiting

This is mostly correct. The only correction I would point out is that the minimal waiting time is calculated through currInterval.start - 1 and it is not necessarily 1.

Another question is why only vertex conflicts and not edge conflicts are selected when calculating the safe time interval of locations.

Only vertex constraints are considered because an edge constraint does not mean the vertex is unsafe. It could be unsafe to reach the vertex through some edge, but safe through another. Edge constraints are handled in 'moveIntoSafeInterval' using 'constraints.accepts()'.

―
